import { FunctionComponent } from "react";
import { PageContainerProps } from "../types/common.types";
import Format from "@/components/Walkthrough/Format/modules/Format";
import Layer from "@/components/Walkthrough/Layer/modules/Layer";
import Synth from "@/components/Walkthrough/Synth/modules/Synth";
import TopBanner from "./TopBanner";
import Composite from "@/components/Walkthrough/Composite/modules/Composite";
import Purchase from "@/components/Walkthrough/Purchase/modules/Purchase";
import templates from "./../../../../public/items/templates.json";

const PageContainer: FunctionComponent<PageContainerProps> = ({
  dispatch,
  template,
  synthLayer,
  layerToSynth,
  shareSet,
  setShareSet,
  scrollRef,
  cartItems,
  synthConfig,
  handleSynth,
  synthLoading,
  presets,
  address,
  profile,
  handleLensSignIn,
  openConnectModal,
  models,
  signInLoading,
  layersLoading,
  printTypeLayers,
  scrollToComposite,
  compositeRef,
  canvasRef,
  handleMouseDown,
  handleMouseUp,
  handleMouseMove,
  newLayersLoading,
  isDragging,
  hex,
  setHex,
  setColorPicker,
  showBottomOptions,
  setShowBottomOptions,
  thickness,
  setThickness,
  brushWidth,
  setBrushWidth,
  router,
  setTool,
  colorPicker,
  tool,
  undo,
  redo,
  handleReset,
  action,
  handleBlur,
  writingRef,
  selectedElement,
  font,
  fontOpen,
  setFont,
  setFontOpen,
  canvasExpand,
  materialBackground,
  materialOpen,
  setEncrypted,
  setMaterialBackground,
  setMaterialOpen,
  completedSynths,
  handleDownloadImage,
  itemClicked,
  setItemClicked,
  controlType,
  setControlType,
  synthRef,
  scrollToPreroll,
  chain,
  openChainModal,
  apiKey,
  handleApproveSpend,
  handleCheckoutCrypto,
  approved,
  cryptoCheckoutLoading,
  fulfillmentDetails,
  oracleValue,
  setCartItem,
  setCheckoutCurrency,
  encryptFulfillment,
  cartItem,
  checkoutCurrency,
  setOpenCountryDropDown,
  openCountryDropDown,
  encrypted,
  setFulfillmentDetails,
  startIndex,
  setStartIndex,
  t,
}): JSX.Element => {
  return (
    <div className="relative w-full h-full flex flex-col gap-5">
      <TopBanner t={t} />
      <div className="relative w-full h-full flex flex-col overflow-y-scroll gap-20 justify-start items-center overflow-x-hidden">
        <Format
          t={t}
          router={router}
          dispatch={dispatch}
          template={template}
          templates={templates}
        />
        <Layer
          t={t}
          router={router}
          layers={printTypeLayers}
          dispatch={dispatch}
          synthLayer={synthLayer}
          layersLoading={layersLoading}
          scrollToPreroll={scrollToPreroll}
        />
        <Synth
          t={t}
          router={router}
          itemClicked={itemClicked}
          setItemClicked={setItemClicked}
          materialBackground={materialBackground}
          setMaterialBackground={setMaterialBackground}
          materialOpen={materialOpen}
          setMaterialOpen={setMaterialOpen}
          controlType={controlType}
          setControlType={setControlType}
          font={font}
          setFont={setFont}
          fontOpen={fontOpen}
          setFontOpen={setFontOpen}
          action={action}
          selectedElement={selectedElement}
          handleBlur={handleBlur}
          writingRef={writingRef}
          tool={tool}
          dispatch={dispatch}
          canvasExpand={canvasExpand}
          layerToSynth={layerToSynth}
          synthLayer={synthLayer}
          synthConfig={synthConfig}
          handleSynth={handleSynth}
          presets={presets}
          synthLoading={synthLoading}
          scrollToComposite={scrollToComposite}
          canvasRef={canvasRef}
          handleMouseDown={handleMouseDown}
          handleMouseUp={handleMouseUp}
          handleMouseMove={handleMouseMove}
          newLayersLoading={newLayersLoading}
          isDragging={isDragging}
          showBottomOptions={showBottomOptions}
          setShowBottomOptions={setShowBottomOptions}
          colorPicker={colorPicker}
          setColorPicker={setColorPicker}
          hex={hex}
          setHex={setHex}
          setThickness={setThickness}
          thickness={thickness}
          setBrushWidth={setBrushWidth}
          brushWidth={brushWidth}
          setTool={setTool}
          undo={undo}
          redo={redo}
          handleReset={handleReset}
          completedSynths={completedSynths}
          handleDownloadImage={handleDownloadImage}
          synthRef={synthRef}
        />
        <Composite
          t={t}
          router={router}
          openChainModal={openChainModal}
          chain={chain}
          dispatch={dispatch}
          setShareSet={setShareSet}
          shareSet={shareSet}
          address={address}
          openConnectModal={openConnectModal}
          handleLensSignIn={handleLensSignIn}
          profile={profile}
          models={models}
          signInLoading={signInLoading}
          compositeRef={compositeRef}
          apiKey={apiKey}
        />
        <Purchase
          router={router}
          chain={chain}
          setEncrypted={setEncrypted}
          lensConnected={profile}
          handleLensSignIn={handleLensSignIn}
          setStartIndex={setStartIndex}
          startIndex={startIndex}
          t={t}
          setFulfillmentDetails={setFulfillmentDetails}
          setCartItem={setCartItem}
          setCheckoutCurrency={setCheckoutCurrency}
          cartItem={cartItem}
          checkoutCurrency={checkoutCurrency}
          oracleValue={oracleValue}
          encryptFulfillment={encryptFulfillment}
          handleApproveSpend={handleApproveSpend}
          handleCheckoutCrypto={handleCheckoutCrypto}
          cryptoCheckoutLoading={cryptoCheckoutLoading}
          approved={approved}
          openChainModal={openChainModal}
          dispatch={dispatch}
          scrollRef={scrollRef}
          cartItems={cartItems}
          signInLoading={signInLoading}
          address={address}
          openConnectModal={openConnectModal}
          fulfillmentDetails={fulfillmentDetails}
          encrypted={encrypted}
          setOpenCountryDropDown={setOpenCountryDropDown}
          openCountryDropDown={openCountryDropDown}
        />
      </div>
    </div>
  );
};

export default PageContainer;
